### ISSUE TITLE
blueimp/nightwatch fails to start since 5996659182c7de3b114430e7a1f88c7fb76765e2

### ISSUE THREAD

**Issue by mathieuhelie** [blueimp/chromedriver#3]
The wait for hosts script cannot connect to chromedriver:4444 and removing wait for hosts functionality indicates that the selenium driver has not connected to port 4444 (but the IP of the chromedriver host has been resolved correctly).

This has been replicated across multiple workstations.

**Comment by mathieuhelie** [comment]
After a lot of troubleshooting we managed to get things moving again by performing the corresponding updates on the docker-compose files and nightwatch containers. This breaks some of our tests, so we have been forced into a maintenance operation.

This is why versioning container images is important. :latest is not sufficient.

**Comment by larowlan** [comment]
Can you elaborate on what you changed here?

**Comment by flaper87** [comment]
@mathieuhelie can you elaborate on what the solution was? I'm having the same issue.

**Comment by mathieuhelie** [comment]
The only change needed was to force an update of the corresponding blueimp/nightwatch container in our docker-compose file (which we had cloned from the blueimp/nightwatch repo), since that one is versioned but the chromedriver container is not, then the push on the chromedriver container left an incompatible version pin on nightwatch in docker-compose (0.9). After merging the docker-compose file with the updated docker-compose in blueimp/nightwatch the incompatibility was resolved.

This required a lot of purging of old containers on everyone's part, so it wasn't painless.

**Comment by flaper87** [comment]
mmh, I managed to solve this yday on my end but it required some extra work.

The chromedriver container won't start for me unless I pass `DISABLE_X11`, which is a new env variable. Disabling X11 then requires setting the `--headless` arg in nightwatch. I wonder if this is supposed to work like this or if my environment is missing something.
